// Colección de 365 Preguntas Filosóficas orientadas al Autoconocimiento y Crecimiento Personal
// Una pregunta para cada día del año (1 a 365). Sin repeticiones durante el ciclo anual.

export const PHILOSOPHICAL_QUESTIONS: string[] = [
  // Enero - Identidad, Inicio & Propósito (1 - 31)
  "¿Quién eres cuando nadie te está observando y tus títulos dejan de importar?",
  "¿Qué promesa que te hiciste a ti mismo necesitas renovar hoy?",
  "¿Qué hábito que mantienes hoy perjudica silenciosamente a tu versión futura?",
  "¿Si pudieras dejar un solo principio como legado a tus descendientes, cuál sería?",
  "¿Qué significa realmente 'tener éxito' según tus propios estándares, no los de la sociedad?",
  "¿En qué área de tu vida estás exigiendo perfección en lugar de buscar constancia?",
  "¿Qué miedo te está impidiendo tomar la decisión que sabes que debes tomar?",
  "¿Cuál ha sido la renuncia más valiosa que has hecho para proteger tu paz mental?",
  "¿Qué conversación difícil has estado postergando y qué temes descubrir en ella?",
  "¿Cómo reaccionas cuando las cosas no salen como planeaste: con frustración o adaptabilidad?",
  "¿A quién admiras profundamente y qué cualidad de esa persona deberías cultivar más?",
  "¿Qué creencia sobre ti mismo te ha limitado durante años y hoy puedes cuestionar?",
  "¿Qué acción sencilla de hoy demuestra que respetas tu propio tiempo?",
  "¿En qué momentos sientes que actúas con mayor autenticidad?",
  "¿Qué le dirías a tu versión de hace diez años si pudieras hablarle cinco minutos?",
  "¿Cómo defines la disciplina: como una carga o como la máxima forma de libertad personal?",
  "¿Qué actividad te hace perder la noción del tiempo y te llena de energía auténtica?",
  "¿Qué error del pasado te ha enseñado tu lección de vida más profunda?",
  "¿Qué responsabilidad estás eludiendo al culpar a las circunstancias externas?",
  "¿Qué tan alineadas están tus acciones diarias con los valores que afirmas tener?",
  "¿Qué significa para ti ser una persona de palabra?",
  "¿Cuándo fue la última vez que cambiaste de opinión sobre algo importante y por qué?",
  "¿Qué hábito o posesión podrías eliminar hoy para simplificar tu vida?",
  "¿Cómo manejas las críticas destructivas: las absorbes o las filtras serenamente?",
  "¿Qué regalo intangible le diste hoy a alguien a tu alrededor?",
  "¿Qué parte de tu carácter necesita más pulimiento en este momento?",
  "¿Si pudieras resolver una sola duda sobre tu futuro, cuál querrías que fuera?",
  "¿En qué momento de esta semana sentiste mayor gratitud sincera?",
  "¿Qué estás construyendo hoy que resistirá la prueba del tiempo?",
  "¿Qué compromiso tienes contigo mismo que no estás cumpliendo?",
  "¿Cómo te recuerdas a ti mismo tu propia mortalidad para priorizar lo esencial?",

  // Febrero - Relaciones, Carácter & Caridad (32 - 59)
  "¿Qué cualidad valoras más en las personas con las que compartes tu vida?",
  "¿A quién necesitas perdonar verdaderamente para liberarte del peso del rencor?",
  "¿En qué medida escuchas para comprender en lugar de escuchar para responder?",
  "¿Qué relación en tu vida requiere más cuidado y presencia de tu parte?",
  "¿Cómo demuestras aprecio a las personas que te apoyan incondicionalmente?",
  "¿Qué límite saludable necesitas establecer con los demás para cuidar tu bienestar?",
  "¿Cuándo fue la última vez que pediste disculpas de manera sincera y humilde?",
  "¿Qué impacto dejas en el estado de ánimo de una habitación cuando entras en ella?",
  "¿Estás buscando aprobación externa en lugares donde deberías buscar convicción interna?",
  "¿Qué acto de generosidad anónima o desinteresada podrías hacer hoy?",
  "¿Cómo manejas el éxito de los demás: te inspira verdaderamente o despierta envidia?",
  "¿Qué persona ha marcado un antes y un después en tu desarrollo y le has agradecido?",
  "¿De qué manera la empatía ha cambiado la perspectiva de tus conflictos recientes?",
  "¿Qué palabra de aliento que no dijiste hoy deberías haber expresado?",
  "¿En qué medida permites que el miedo al rechazo condicione tus expresiones de afecto?",
  "¿Qué hábitos de comunicación podrías mejorar para evitar malentendidos innecesarios?",
  "¿Cómo puedes ser un mejor refugio o apoyo para tu familia y seres queridos?",
  "¿Qué prejuicio sobre otra persona descubriste recientemente que era infundado?",
  "¿Qué significa ser un verdadero amigo cuando la situación se vuelve exigente?",
  "¿Qué comportamiento en los demás te molesta más y qué refleja sobre ti mismo?",
  "¿Cómo equilibras la firmeza en tus principios con la amabilidad hacia las personas?",
  "¿Qué aprendiste hoy al observar la actitud de alguien a quien respetas?",
  "¿A qué amigo lejano te gustaría contactar hoy solo para saber cómo se encuentra?",
  "¿Qué sacrificio por el bien de otra persona valió totalmente la pena?",
  "¿Cómo reaccionas ante la vulnerabilidad ajena y qué tan dispuesto estás a mostrar la tuya?",
  "¿Qué legado afectivo quieres dejar en las personas que conviven contigo?",
  "¿De qué manera nutres la confianza mutua en tus relaciones más cercanas?",
  "¿Qué lección sobre el amor y el respeto has aprendido con los años?",

  // Marzo - Disciplina, Trabajo & Mente (60 - 90)
  "¿Qué distingue a una persona con fuerza de voluntad de una que depende de la motivación?",
  "¿Qué distracciones cotidianas roban tu atención y cómo planeas reducir su impacto?",
  "¿Cómo conviertes un día ordinario en una jornada de crecimiento intencional?",
  "¿Qué tarea desagradable estás postergando que te daría alivio inmediato al completarla?",
  "¿Cuál es tu actitud frente a la frustración cuando un objetivo se retrasa?",
  "¿Cómo alimentas tu mente cada día: con información basura o con conocimiento reflexivo?",
  "¿Qué libro, idea o enseñanza ha transformado más tu forma de pensar este año?",
  "¿Qué significa para ti el trabajo bien hecho, independientemente de que alguien lo supervise?",
  "¿Qué hábito de descanso o recuperación necesitas priorizar para mantener tu claridad mental?",
  "¿En qué proyecto o causa pondrías toda tu energía si supieras que no vas a fracasar?",
  "¿Cómo reaccionas cuando cometes un error profesional: lo asumes o buscas justificaciones?",
  "¿Qué habilidad mental o técnica necesitas desarrollar para alcanzar tu siguiente nivel?",
  "¿Qué tan tolerante eres con la incertidumbre cuando no tienes el control absoluto?",
  "¿De qué manera proteges tus primeros minutos del día de las urgencias ajenas?",
  "¿Qué pensamiento recurrente deberías desechar hoy porque no aporta ninguna solución?",
  "¿Cómo mides tu productividad: por la cantidad de actividades o por el valor de los resultados?",
  "¿Qué pequeña victoria de hoy merece ser reconocida en tu diario?",
  "¿Qué estrategia usas para mantener la calma cuando aumenta la presión externa?",
  "¿Cómo cultivas la paciencia en un mundo que exige inmediatez constante?",
  "¿Qué significa para ti ser mentalmente fuerte frente a las adversidades?",
  "¿Qué aprendes de los momentos de aburrimiento o silencio cuando no usas pantallas?",
  "¿Qué patrón destructivo en tus rutinas has logrado romper con éxito?",
  "¿Cómo conviertes los obstáculos imprevistos en oportunidades para ejercitar virtudes?",
  "¿Qué decisión tomada bajo estrés habrías cambiado con más calma?",
  "¿Qué estándar personal no estás dispuesto a rebajar bajo ninguna circunstancia?",
  "¿Qué significa para ti la excelencia frente a la mediocridad?",
  "¿Cómo garantizas que tus metas diarias respondan a tus verdaderas prioridades de vida?",
  "¿Qué hábito de organización te ha ahorrado más energía mental en los últimos meses?",
  "¿En qué momentos sientes que estás en tu punto máximo de claridad y enfoque?",
  "¿Qué lección de humildad te dejó hoy tu trabajo o tus estudios?",
  "¿Cómo cuidas la coherencia entre lo que piensas, lo que dices y lo que ejecutas?",

  // Abril - Miedos, Resiliencia & Coraje (91 - 120)
  "¿Qué miedo oculto está dirigiendo algunas de tus decisiones sin que te des cuenta?",
  "¿Cuándo fue la última vez que actuaste con coraje a pesar de sentir temblor en las manos?",
  "¿Qué peor escenario te imaginas y qué tan capaz serías de sobreponerte si ocurriera?",
  "¿De qué manera el fracaso ha sido un mejor maestro en tu vida que el triunfo?",
  "¿Qué terreno desconocido te genera resistencia explorar y por qué?",
  "¿Cómo distingues entre una prudencia genuina y una excusa disfrazada de cautela?",
  "¿Qué parte de tu zona de confort necesitas abandonar para seguir evolucionando?",
  "¿Qué narrativa dolorosa sobre tu pasado puedes reescribir hoy con mayor madurez?",
  "¿Qué crítica temes recibir y qué pasaría si simplemente la ignoraras?",
  "¿En qué situación reciente elegiste la comodidad sobre lo que sabías que era correcto?",
  "¿Cómo fortaleces tu carácter cuando la vida se vuelve exigente e incierta?",
  "¿Qué herida emocional del pasado ha dejado una cicatriz que hoy te hace más fuerte?",
  "¿Qué opinión popular o presión social te niegas a adoptar por convicción personal?",
  "¿Qué decisión de tu vida te ha enseñado más, aunque en su momento pareciera un error?",
  "¿Cómo mantienes la esperanza en momentos donde no ves resultados inmediatos?",
  "¿Qué aspecto de tu vulnerabilidad te cuesta más aceptar frente a los demás?",
  "¿De qué manera manejas la decepción cuando alguien no responde como esperabas?",
  "¿Qué batalla interna estás librando actualmente de la cual casi nadie sabe?",
  "¿Qué recuerdo doloroso ha perdido fuerza con el paso del tiempo y qué aprendiste de él?",
  "¿Cómo te recuerdas que la incomodidad es el precio inevitable del crecimiento?",
  "¿Qué paso audaz podrías dar esta semana para acercarte a tus metas?",
  "¿Qué lección de resiliencia has aprendido de las dificultades que atravesó tu familia?",
  "¿Cómo evitas victimizarte cuando enfrentas una racha de mala suerte o imprevistos?",
  "¿Qué convicción tienes hoy que defenderías aunque te quedaras solo en la postura?",
  "¿Qué capacidad de recuperación que ignorabas tener descubriste en ti mismo?",
  "¿Cómo transformas el nerviosismo o la ansiedad en entusiasmo enfocado?",
  "¿Qué verdad incómoda sobre ti mismo estás listo para reconocer hoy?",
  "¿De qué manera el coraje ha cambiado el rumbo de tu vida en momentos cruciales?",
  "¿Qué significa para ti morir en paz con tu conciencia al final del día?",
  "¿Qué victoria silenciosa sobre tus propias debilidades lograste recientemente?",

  // Mayo - Tiempo, Simplicidad & Gratitud (121 - 151)
  "¿Si el tiempo fuera tu bien más escaso, a qué le restarías horas a partir de hoy?",
  "¿Qué detalle de tu entorno inmediato ignoras a diario pero podrías agradecer profundamente?",
  "¿Cómo influye la prisa en la calidad de tus pensamientos y de tus decisiones?",
  "¿Qué momento de silencio en el día te reconecta con lo esencial?",
  "¿Qué posesión material tienes que realmente no necesitas y podrías regalar o soltar?",
  "¿Cómo experimentas la plenitud en el presente sin estar angustiado por el futuro?",
  "¿Qué actividad sencilla te produce una sensación de paz incontestable?",
  "¿Qué hábito podrías simplificar para ganar espacio mental y energía?",
  "¿A quién le debes un agradecimiento sincero por una ayuda recibida en el pasado?",
  "¿Cómo cambia tu día cuando comienzas con una actitud activa de gratitud?",
  "¿Qué aspecto de tu salud física descuidas cuando te enfocas en exceso en el trabajo?",
  "¿Qué significa para ti vivir una vida liviana y libre de cargas innecesarias?",
  "¿Qué recuerdo de la infancia conserva aún su magia para ti?",
  "¿Cómo evitas la tentación de comparar tu proceso personal con el de los demás?",
  "¿Qué bendición cotidiana estás dando por sentada simplemente porque es frecuente?",
  "¿Qué regalo intangible pero de inmenso valor recibiste en las últimas semanas?",
  "¿Cómo puedes cultivar más serenidad en medio del ruido del entorno?",
  "¿Qué espacio de tu hogar o lugar de trabajo necesita orden para reflejar paz mental?",
  "¿Qué conversación sobre cosas profundas disfrutaste recientemente?",
  "¿Qué significa para ti saborear el camino en lugar de obsesionarte con la llegada?",
  "¿Qué actividad al aire libre o en contacto con la naturaleza podrías planear pronto?",
  "¿De qué manera la sobriedad y la templanza mejoran tu calidad de vida?",
  "¿Qué hábito de consumo innecesario te gustaría eliminar permanentemente?",
  "¿Cómo respondes al regalo de un nuevo día cada mañana al despertar?",
  "¿Qué momento del día de hoy guardarías en una cápsula del tiempo?",
  "¿Qué lección de humildad te deja observar el cielo o la inmensidad del universo?",
  "¿De qué manera puedes simplificar tus expectativas sobre las personas para sufrir menos?",
  "¿Qué canto, lectura o melodía calma tu espíritu en momentos de turbulencia?",
  "¿Qué gesto de amabilidad recibido recientemente no vas a olvidar?",
  "¿Cómo recuerdas que el tiempo es un recurso no renovable que corre continuamente?",
  "¿Qué gratitud especial sientes hoy por estar con vida y con capacidad de razonar?",

  // Junio - Virtudes, Ética & Carácter (152 - 181)
  "¿Cuál es la virtud estoica o moral que más necesitas practicar en este periodo de tu vida?",
  "¿Cómo actúas cuando nadie te puede sancionar si rompes una regla implícita?",
  "¿Qué concesión a la pereza o a la mediocridad hiciste hoy que deberías corregir?",
  "¿Qué significa para ti la integridad cuando hay mucho que ganar si mientes?",
  "¿De qué manera tu paciencia fue puesta a prueba hoy y cómo reaccionaste?",
  "¿Qué tentación de vanidad o soberbia detectaste en tus pensamientos recientes?",
  "¿Cómo demuestras templanza frente a los excesos o a las gratificaciones instantáneas?",
  "¿Qué decisión éticamente compleja has tenido que tomar y cómo protegiste tu conciencia?",
  "¿En qué medida la ecuanimidad guía tus respuestas emocionales intensas?",
  "¿Qué es para ti la justicia en el trato cotidiano con quienes tienen menos poder que tú?",
  "¿Cómo reaccionas ante la injusticia: con rabia destructiva o con acción firme y noble?",
  "¿Qué significa ser maestro de ti mismo en lugar de ser esclavo de tus impulsos?",
  "¿De qué manera la honestidad brutal pero respetuosa te ha salvado de confusiones?",
  "¿Qué hábito de autodisciplina ha mejorado tu autoestima en los últimos meses?",
  "¿Qué defecto de tu carácter estás trabajando de forma activa con mayor perseverancia?",
  "¿Cómo mantienes la dignidad personal frente a humillaciones o faltas de respeto?",
  "¿Qué lección de sabiduría has obtenido de una persona mayor que tú?",
  "¿De qué manera tus hábitos financieros reflejan o contradicen tus principios morales?",
  "¿Qué significa para ti tener un corazón noble pero una mente aguda e inflexible con la mentira?",
  "¿Cómo cultivas la humildad cuando logras un hito importante o un reconocimiento?",
  "¿Qué promesa no escrita mantienes con tu comunidad o con tu país?",
  "¿Qué lección sobre la templanza has aprendido por las malas tras cometer un exceso?",
  "¿Cómo actúas frente al chisme o los comentarios malévolos sobre personas ausentes?",
  "¿Qué valor personal jamás estarías dispuesto a vender por ninguna suma de dinero?",
  "¿Cómo se manifiesta la firmeza moral en tus momentos de mayor soledad?",
  "¿Qué responsabilidad social o comunitaria estás llamado a asumir más de cerca?",
  "¿Qué lección te deja observar a una persona que actúa con total integridad impecable?",
  "¿Cómo equilibras la firmeza en tus juicios con la compasión por la fragilidad humana?",
  "¿Qué significa para ti llevar una vida guiada por la razón y la virtud?",
  "¿Qué compromiso renovado con tu crecimiento moral asumes para la segunda mitad del año?",

  // Julio - Identidad, Evaluación a Mitad de Año & Dirección (182 - 212)
  "¿Si evaluaras tu primer semestre del año, cuál ha sido tu mayor acierto y tu peor descuido?",
  "¿En qué medida el rumbo actual de tu vida te entusiasma verdaderamente al despertar?",
  "¿Qué objetivo que fijaste al iniciar el año ha dejado de tener sentido y debes soltar?",
  "¿Qué nueva meta o sueño exige tu atención enfocada para los próximos meses?",
  "¿Qué faceta de tu personalidad ha cambiado más en el último año?",
  "¿De qué ilusiones o autoengaños te has liberado recientemente?",
  "¿Qué rol juegas en tu propio sufrimiento cuando sobrepiensas los problemas?",
  "¿Cómo defines la madurez personal y qué tan cerca te sientes de esa definición?",
  "¿Qué parte de tu rutina diaria te genera la mayor paz y satisfacción interior?",
  "¿Qué hábito de salud física necesitas corregir antes de que se convierta en una factura?",
  "¿Qué frontera emocional necesitas cruzar para experimentar mayor plenitud?",
  "¿Cómo te aseguras de que no estás viviendo la vida que otros diseñaron para ti?",
  "¿Qué talentos o dones naturales posees que no estás utilizando lo suficiente?",
  "¿Qué lección te deja comparar tu vida real con las expectativas que tenías hace 5 años?",
  "¿De qué manera la soledad elegida fortalece tu identidad y tu autoconocimiento?",
  "¿Qué pensamiento te ayuda a recobrar el eje cuando sientes que pierdes el control?",
  "¿Cómo cultivas el agradecimiento por tus fortalezas sin caer en la complacencia?",
  "¿Qué historia te cuentas a ti mismo cuando justificas no empezar algo importante?",
  "¿Qué cambio de entorno o de círculo social impulsaría tu desarrollo personal?",
  "¿Qué lección sobre el tiempo te deja ver cómo se han ido volando los últimos meses?",
  "¿Cómo se ve para ti el equilibrio entre ambición sana y paz con el presente?",
  "¿Qué cualidad de tu carácter ha sido puesta a prueba en las últimas semanas?",
  "¿De qué manera la paciencia ha evitado que cometas un error impulsivo reciente?",
  "¿Qué actividad creativa o intelectual te gustaría incorporar a tus fines de semana?",
  "¿Cómo honras el legado de esfuerzo que tus padres o antecesores pusieron en ti?",
  "¿Qué lección de sabiduría aplicaste hoy para resolver un dilema ordinario?",
  "¿Qué área de tu hogar o trabajo necesita una renovación o limpieza profunda?",
  "¿Cómo respondes cuando la vida te pide cambiar de plan a mitad de camino?",
  "¿Qué significa para ti ser una persona verdaderamente libre e independiente?",
  "¿Qué hábito de lectura o estudio vas a comprometerte a cultivar este mes?",
  "¿Qué reflexión sobre tu vida te deja el día de hoy?",

  // Agosto - Madurez, Carácter & Filosofía de Vida (213 - 243)
  "¿Qué significa para ti la paz mental y qué precio estás dispuesto a pagar por ella?",
  "¿Cómo reaccionas cuando descubres que estabas equivocado en un argumento?",
  "¿Qué verdad incómoda prefieres ignorar hoy para no tener que actuar?",
  "¿Qué diferencia existe entre reaccionar por impulso y responder con serenidad?",
  "¿Qué lección te ha enseñado el dolor físico o emocional sobre tu propia resistencia?",
  "¿Cómo cuidas la energía que transmites a tus seres queridos al llegar a casa?",
  "¿Qué hábito nocturno deberías cambiar para dormir mejor y despertar con claridad?",
  "¿De qué manera la brevedad de la vida cambia tus prioridades inmediatas?",
  "¿Qué persona requiere hoy que le escuches sin juzgarla ni darle consejos no pedidos?",
  "¿Cómo mantienes la calma en entornos donde reina el drama o la negatividad?",
  "¿Qué lección de ecuanimidad has aprendido de los reveses inesperados?",
  "¿Qué hábito de gratitud te ayuda a transformar un día difícil en un día valioso?",
  "¿Cómo proteges tus pensamientos de la manipulación, el miedo o el sensacionalismo?",
  "¿Qué compromiso con tu salud física has descuidado y debes retomar hoy?",
  "¿Qué conversación interna contigo mismo necesitas cambiar porque te destruye?",
  "¿Qué significa ser riguroso con uno mismo pero comprensivo con las fallas ajenas?",
  "¿De qué manera la disciplina silenciosa construye más carácter que los discursos?",
  "¿Qué lección de autocontrol aplicaste hoy cuando sentiste ganas de explotar?",
  "¿Qué aprendizaje sobre la naturaleza humana has confirmado con tus experiencias?",
  "¿Cómo te recuperas de un día en el que sientes que no rendiste como esperabas?",
  "¿Qué hábito de organización reduce la fricción en tus mañanas?",
  "¿Qué valor ético te sostuvo firme en tu última decisión difícil?",
  "¿Cómo celebras tus pequeños avances sin perder el impulso por mejorar?",
  "¿Qué actitud frente a la vejez o el paso de los años estás cultivando?",
  "¿Qué lección te deja ver a personas que han arruinado su vida por falta de carácter?",
  "¿Cómo evitas guardar rencores que solo envenenan tu propio corazón?",
  "¿Qué pequeña acción de hoy te hizo sentir orgulloso de ti mismo?",
  "¿Qué principio de vida no cambiarías ni por todo el dinero del mundo?",
  "¿Cómo respondes ante la ingratitud de alguien a quien ayudaste de buena fe?",
  "¿Qué lugar especial te reconecta con tu esencia y cuándo volverás a él?",
  "¿Qué lección sobre la constancia te deja la persistencia en tus objetivos?",

  // Septiembre - Crecimiento, Educación & Sabiduría (244 - 273)
  "¿Qué conocimiento o destreza nueva has adquirido este mes que amplía tu visión?",
  "¿Cómo alimentas tu curiosidad intelectual en medio de tus ocupaciones diarias?",
  "¿Qué maestro o figura de mentoría ha tenido la mayor influencia en tu rigor mental?",
  "¿De qué manera la lectura constante ha moldeado tu capacidad de reflexión?",
  "¿Qué idea preconcebida que tenías sobre el mundo se ha derrumbado recientemente?",
  "¿Cómo evitas la arrogancia cuando aprendes algo que la mayoría ignora?",
  "¿Qué pregunta profunda deberías hacerte más seguido antes de tomar una decisión?",
  "¿Qué significa para ti pensar por ti mismo en lugar de seguir a la multitud?",
  "¿Cómo aplicas la lógica y la razón para desarmar miedos irracionales?",
  "¿Qué hábito de escritura o diario te ayuda a poner en orden el caos mental?",
  "¿De qué manera la filosofía o la fe te brindan un marco para interpretar el sufrimiento?",
  "¿Qué lección te deja analizar las consecuencias a largo plazo de tus decisiones pasadas?",
  "¿Cómo distingues entre un deseo genuino de tu alma y una necesidad creada por el entorno?",
  "¿Qué destreza difícil requiere más horas de práctica deliberada de tu parte?",
  "¿Qué lección de humildad aprendes al reconocer lo mucho que aún ignoras?",
  "¿Cómo puedes ser un mejor transmisor de valores y conocimientos para los más jóvenes?",
  "¿Qué patrón en la historia humana se repite hoy en tu propia vida cotidiana?",
  "¿Qué actitud adoptas frente a las materias o temas que te cuestan trabajo entender?",
  "¿De qué manera la observación atenta de la naturaleza te enseña sobre los ciclos de la vida?",
  "¿Qué decisión intelectual o de estudio ha sido la más rentable para tu crecimiento?",
  "¿Cómo te aseguras de que el conocimiento adquirido se convierta en sabiduría aplicada?",
  "¿Qué libro releerías cada año porque siempre te descubre capas de significado nuevas?",
  "¿Qué hábito mental te ayuda a encontrar simplicidad en problemas complejos?",
  "¿Cómo mantienes viva la capacidad de asombro ante las maravillas cotidianas?",
  "¿Qué lección te deja un error que cometiste por exceso de confianza?",
  "¿De qué manera la ecuanimidad intelectual te previene de caer en fanatismos?",
  "¿Qué espacio sagrado de tu día reservas para pensar sin interrupciones?",
  "¿Cómo mides el verdadero valor de una idea: por su elegancia o por su utilidad ética?",
  "¿Qué principio pedagógico o de enseñanza aplicas contigo mismo cuando fallas?",
  "¿Qué descubrimiento personal sobre tu mente te ha sorprendido gratamente este mes?",

  // Octubre - Resistencia, Carácter Bajo Presión & Valores (274 - 304)
  "¿Cómo mantienes tus principios firmes cuando todos a tu alrededor toman atajos?",
  "¿Qué significa la templanza cuando enfrentas provocaciones directas o faltas de respeto?",
  "¿Qué carga innecesaria estás arrastrando que deberías soltar antes de terminar el año?",
  "¿De qué manera el autodominio te distingue como un líder o referente en tu entorno?",
  "¿Qué tentación de vanidad o validación en redes sociales deberías frenar hoy?",
  "¿Cómo reaccionas cuando una meta por la que trabajaste duro se derrumba al final?",
  "¿Qué lección de dignidad te deja mantener la compostura en la derrota?",
  "¿Cómo usas los momentos de cansancio físico para entrenar tu fortaleza mental?",
  "¿Qué frontera de esfuerzo nunca habías explorado y hoy te atreves a tocar?",
  "¿De qué manera la moderación en los placeres fortalece la claridad de tu propósito?",
  "¿Qué significa ser una roca de serenidad para tu familia en momentos de crisis?",
  "¿Qué lección te deja haber sobrevivido a tus peores días del pasado?",
  "¿Cómo proteges tus ideales de la amargura o del cinismo del mundo?",
  "¿Qué hábito de autodisciplina no negociable mantendrás sin importar las circunstancias?",
  "¿De qué manera la veracidad absoluta en tus palabras te construye una reputación sólida?",
  "¿Qué sacrificios valen la pena hacer hoy por la tranquilidad de tu futuro?",
  "¿Cómo evitas la trampa del perfeccionismo que paraliza la ejecución activa?",
  "¿Qué lección te deja haber perdonado a alguien que no mostró arrepentimiento?",
  "¿Cómo renuevas tus energías cuando sientes agotamiento de voluntad?",
  "¿Qué pensamiento estoico o filosófico te rescata en momentos de opresión?",
  "¿Qué pequeña renuncia de hoy te hace sentir más dueño de tus acciones?",
  "¿Cómo conviertes la envidia ajena o la hostilidad en combustible para la excelencia?",
  "¿Qué aspecto de tu carácter se fortalece más cuando trabajas en silencio?",
  "¿De qué manera la sobriedad en tus palabras evita conflictos innecesarios?",
  "¿Qué lección sobre el respeto a los compromisos asumiste como bandera personal?",
  "¿Cómo actúas cuando las cosas se ponen difíciles: te encoges o te creces?",
  "¿Qué hábito de higiene mental practicas para irte a dormir con la mente limpia?",
  "¿Qué valor moral ha guiado tus momentos más oscuros y nunca te ha fallado?",
  "¿Cómo vives con la certeza de que el tiempo de vida es limitado e irrecuperable?",
  "¿Qué lección de coraje te dio hoy una persona que lucha contra la adversidad?",
  "¿Qué agradecimiento especial le rindes a tu propia firmeza por haber llegado hasta aquí?",

  // Noviembre - Reflexión, Cierre & Trascendencia (305 - 334)
  "¿Cómo se ve el balance general de tu crecimiento en lo que va del año?",
  "¿Qué deudas de afecto, disculpa o gratitud quieres saldar antes de que termine el año?",
  "¿De qué manera la serenidad se ha convertido en una prioridad en tus días?",
  "¿Qué viejo hábito peligroso amagó con regresar este mes y cómo lo frenaste?",
  "¿Qué significado tiene para ti la paz de la conciencia limpia al apoyar la cabeza en la almohada?",
  "¿Cómo demuestras aprecio a las personas que hacen tu vida diaria más fácil y amable?",
  "¿Qué lección sobre la brevedad del tiempo te deja el viento de fin de año?",
  "¿Cómo manejas la nostalgia de tiempos pasados sin descuidar tu presente activo?",
  "¿Qué logro silencioso de este año nadie más conoce pero para ti significa todo?",
  "¿De qué manera has aprendido a ser más amable contigo mismo sin caer en la laxitud?",
  "¿Qué hábito de ahorro o prudencia financiera te dará tranquilidad el próximo año?",
  "¿Qué conversación franca contigo mismo ha despejado tus dudas sobre el futuro?",
  "¿How react at the change of seasons and how does it inspire your internal renewal?",
  "¿Qué parte de tu ego necesitó ser destruida para que tu verdadero ser floreciera?",
  "¿De qué manera te has convertido en un mejor protector de tus seres queridos?",
  "¿Qué promesa de año que parecía imposible se ha ido convirtiendo en realidad con constancia?",
  "¿Cómo evitas que el ruido de las fiestas o cierres de año te aparte de lo esencial?",
  "¿Qué hábito de generosidad sincera puedes practicar con alguien que no puede corresponderte?",
  "¿De qué manera la moderación te evita los guayabos morales o financieros?",
  "¿Qué lección sobre la fragilidad de la vida te ha conmovido recientemente?",
  "¿How guardas el equilibrio entre recordar tus raíces y proyectar tu futuro?",
  "¿Qué hábito de presencia plena ejercitaste hoy con quienes amas?",
  "¿De qué manera el desapego de los resultados te permite disfrutar más el proceso?",
  "¿Qué lección de carácter te ha dejado este mes de trabajo y perseverancia?",
  "¿How cultivas la gratitud por las pruebas duras que superaste con éxito?",
  "¿Qué aspecto de tu madurez emocional te hace sentir mayor seguridad en ti mismo?",
  "¿De qué manera tu fe o filosofía de vida le da sentido a tus esfuerzos diarios?",
  "¿What decision de simplificar tu vida ha sido la más acertada de este año?",
  "¿How mantienes encendida la llama de tu propósito en días de rutina pesada?",
  "¿What legado de paz interior deseas regalarte a ti mismo para el mes que entra?",

  // Diciembre - Gratitud, Trascendencia & Renovación Anual (335 - 365)
  "¿Si tuvieras que resumir el año entero en una sola palabra, cuál sería y por qué?",
  "¿Qué es lo más valioso que aprendiste sobre ti mismo durante los últimos doce meses?",
  "¿A quién le debes la mayor gratitud por haber creído en ti cuando dudabas?",
  "¿Qué hábito que iniciaste este año se ha convertido en una columna vertebral de tu vida?",
  "¿De qué error cometido este año te has perdonado completamente?",
  "¿Qué victoria sobre el miedo te ha abierto las puertas a una mayor libertad personal?",
  "¿How ha cambiado tu definición de la felicidad desde el 1 de enero hasta hoy?",
  "¿Qué persona ha sido tu mayor maestro inesperado este año, incluso a través de un conflicto?",
  "¿What hábito destructivo quedó definitivamente enterrado en tu pasado este año?",
  "¿How cuidas la paz de tu hogar durante las celebraciones y reuniones familiares?",
  "¿What momento de pura alegría y gratitud vivida este año llevarás siempre en el corazón?",
  "¿De qué manera la constancia diaria ha demostrado ser superior al talento sin disciplina?",
  "¿What lección de madurez le dejas como testimonio a tu familia al cerrar este ciclo?",
  "¿How te aseguras de no repetir en el año que viene las fallas que identificaste en este?",
  "¿What regalo de tiempo o atención le darás hoy a la persona que más lo necesita?",
  "¿De qué manera tu carácter se ha vuelto más sólido, noble y compasivo este año?",
  "¿What compromiso no negociable contigo mismo asumirás para la nueva etapa?",
  "¿How recuerdas a las personas amadas que ya no están y cómo honras su memoria viviendo con virtud?",
  "¿What pequeña semilla de bien sembraste este año que dará frutos en el futuro?",
  "¿De qué manera la paciencia ha sido tu mejor aliada en los momentos de incertidumbre?",
  "¿What lección sobre el valor del trabajo honesto te llena de satisfacción al mirar atrás?",
  "¿How te preparas mental y espiritualmente para soltar lo viejo y recibir lo nuevo con valentía?",
  "¿What aspecto de tu salud o bienestar físico agradeces profundamente el día de hoy?",
  "¿De qué manera has aprendido a no buscar fuera lo que solo puedes encontrar dentro de ti?",
  "¿What acto de generosidad discreta hizo sonreír a alguien este mes?",
  "¿How mantienes la calma y la sobriedad en medio de los excesos de fin de año?",
  "¿What lección de sabiduría estoica te acompañará como lema para el próximo ciclo?",
  "¿What sueño que parecía lejano hoy está a solo unos pasos gracias a tu disciplina?",
  "¿How agradeces el regalo inestimable de haber vivido este año completo con lucidez?",
  "¿What mensaje final le dejas escrito a tu futuro yo para que lo lea cuando vacile?",
  "¿Al mirar atrás en 365 días de reflexión, de qué manera te has convertido en el verdadero comandante de tu vida?"
];

/**
 * Retorna la pregunta correspondiente al día del año de una fecha (YYYY-MM-DD)
 */
export function getQuestionForDate(dateStr?: string): { index: number; total: number; question: string } {
  let targetDate: Date;
  if (dateStr) {
    const [y, m, d] = dateStr.split('-').map(Number);
    targetDate = new Date(y, m - 1, d, 12, 0, 0);
  } else {
    targetDate = new Date();
  }

  const startOfYear = new Date(targetDate.getFullYear(), 0, 0);
  const diff = (targetDate.getTime() - startOfYear.getTime()) + ((startOfYear.getTimezoneOffset() - targetDate.getTimezoneOffset()) * 60 * 1000);
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay); // 1..366

  // Mapeo seguro a índice 0..364 (365 preguntas)
  const zeroIndex = ((dayOfYear - 1) % 365 + 365) % 365;

  return {
    index: zeroIndex + 1,
    total: 365,
    question: PHILOSOPHICAL_QUESTIONS[zeroIndex] || PHILOSOPHICAL_QUESTIONS[0]
  };
}
